"""Technology vocabulary used by the truth layer.

The list does not need to be exhaustive. Its job is to catch the common failure mode
where a model garnishes a bullet with a plausible technology the user never listed.
Any term that appears in the user's own records is added to the allowed set at runtime,
so an unusual in-house tool is never blocked.
"""

from __future__ import annotations

TECH_TERMS: frozenset[str] = frozenset(
    {
        # languages
        "python",
        "java",
        "javascript",
        "typescript",
        "go",
        "golang",
        "rust",
        "c",
        "c++",
        "c#",
        "ruby",
        "php",
        "scala",
        "kotlin",
        "swift",
        "r",
        "matlab",
        "perl",
        "bash",
        "shell",
        "sql",
        "plsql",
        "t-sql",
        "vba",
        "dart",
        "elixir",
        "haskell",
        "clojure",
        # data / analytics
        "spark",
        "pyspark",
        "hadoop",
        "hive",
        "presto",
        "trino",
        "airflow",
        "dagster",
        "prefect",
        "dbt",
        "kafka",
        "flink",
        "beam",
        "snowflake",
        "redshift",
        "bigquery",
        "databricks",
        "tableau",
        "looker",
        "power bi",
        "powerbi",
        "superset",
        "metabase",
        "pandas",
        "numpy",
        "scikit-learn",
        "sklearn",
        "pytorch",
        "tensorflow",
        "keras",
        "xgboost",
        "lightgbm",
        "mlflow",
        "sagemaker",
        "huggingface",
        "langchain",
        # databases
        "postgres",
        "postgresql",
        "mysql",
        "mariadb",
        "sqlite",
        "oracle",
        "sql server",
        "mongodb",
        "cassandra",
        "dynamodb",
        "redis",
        "elasticsearch",
        "opensearch",
        "neo4j",
        "clickhouse",
        "duckdb",
        "cockroachdb",
        "firestore",
        "couchbase",
        # cloud / devops
        "aws",
        "azure",
        "gcp",
        "google cloud",
        "kubernetes",
        "k8s",
        "docker",
        "terraform",
        "pulumi",
        "ansible",
        "puppet",
        "chef",
        "jenkins",
        "circleci",
        "github actions",
        "gitlab ci",
        "argocd",
        "helm",
        "prometheus",
        "grafana",
        "datadog",
        "splunk",
        "new relic",
        "sentry",
        "opentelemetry",
        "cloudformation",
        "lambda",
        "ecs",
        "eks",
        "s3",
        "ec2",
        "rds",
        "sqs",
        "sns",
        "kinesis",
        "glue",
        "athena",
        "step functions",
        # web / app
        "react",
        "next.js",
        "nextjs",
        "vue",
        "angular",
        "svelte",
        "node",
        "node.js",
        "express",
        "django",
        "flask",
        "fastapi",
        "spring",
        "spring boot",
        "rails",
        "laravel",
        ".net",
        "asp.net",
        "graphql",
        "rest",
        "grpc",
        "tailwind",
        "bootstrap",
        "redux",
        "jquery",
        "webpack",
        "vite",
        "playwright",
        "selenium",
        "cypress",
        "jest",
        "pytest",
        "junit",
        "mocha",
        # practices / platforms
        "git",
        "github",
        "gitlab",
        "bitbucket",
        "jira",
        "confluence",
        "figma",
        "salesforce",
        "sap",
        "workday",
        "servicenow",
        "hubspot",
        "stripe",
        "twilio",
        "shopify",
        "kubeflow",
        "terraform cloud",
        "linux",
        "unix",
        "windows",
        "macos",
    }
)

#: Claims the platform will never generate, regardless of confidence. Each of these is
#: either legally significant or unverifiable from a resume, so it must come from an
#: explicit user-provided field or not at all.
FORBIDDEN_CLAIM_PATTERNS: tuple[tuple[str, str], ...] = (
    (r"(?i)\b(?:security\s+)?clearance\b", "security clearance"),
    (r"(?i)\btop[\s-]secret\b", "security clearance"),
    (r"(?i)\bwork\s+authoriz(?:ation|ed)\b", "work authorization"),
    (r"(?i)\b(?:visa|sponsorship|green\s+card|h-?1b|opt|cpt)\b", "work authorization"),
    (r"(?i)\bcitizen(?:ship)?\b", "citizenship"),
    (r"(?i)\bsalary\s+history\b", "salary history"),
    (r"(?i)\b(?:veteran|disabilit(?:y|ies)|ethnicity|race|gender)\b", "protected characteristic"),
)

#: Words that carry no evidential weight when measuring grounding overlap.
STOPWORDS: frozenset[str] = frozenset(
    {
        "a",
        "an",
        "and",
        "the",
        "of",
        "for",
        "to",
        "in",
        "on",
        "with",
        "by",
        "at",
        "from",
        "as",
        "that",
        "this",
        "it",
        "is",
        "was",
        "were",
        "be",
        "been",
        "are",
        "or",
        "our",
        "their",
        "its",
        "into",
        "across",
        "over",
        "per",
        "via",
        "using",
        "used",
        "use",
        "including",
        "which",
        "while",
        "than",
        "then",
        "also",
        "more",
        "most",
        "new",
        "team",
        "teams",
        "work",
        "worked",
        "working",
        "responsible",
        "helped",
        "help",
    }
)
