"""User profile: personal, professional, work authorization, and the record tables the
Resume Truth Layer treats as sources of truth."""

from __future__ import annotations

import uuid
from datetime import date

from sqlalchemy import (
    Boolean,
    Date,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from jobapply_db.base import (
    Base,
    JSONColumn,
    SoftDeleteMixin,
    TimestampMixin,
    UUIDColumn,
    UUIDPrimaryKeyMixin,
)


class Profile(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = "profiles"
    __table_args__ = (UniqueConstraint("user_id", name="uq_profiles_user_id"),)

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUIDColumn, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # -- personal -----------------------------------------------------------
    first_name: Mapped[str | None] = mapped_column(String(120))
    last_name: Mapped[str | None] = mapped_column(String(120))
    preferred_name: Mapped[str | None] = mapped_column(String(120))
    email: Mapped[str | None] = mapped_column(String(320))
    phone: Mapped[str | None] = mapped_column(String(40))
    city: Mapped[str | None] = mapped_column(String(120))
    state: Mapped[str | None] = mapped_column(String(120))
    country: Mapped[str | None] = mapped_column(String(120))
    postal_code: Mapped[str | None] = mapped_column(String(20))
    linkedin_url: Mapped[str | None] = mapped_column(String(500))
    github_url: Mapped[str | None] = mapped_column(String(500))
    portfolio_url: Mapped[str | None] = mapped_column(String(500))

    # -- professional -------------------------------------------------------
    current_title: Mapped[str | None] = mapped_column(String(200))
    years_experience: Mapped[float | None] = mapped_column(Numeric(4, 1))
    summary: Mapped[str | None] = mapped_column(Text)
    desired_titles: Mapped[list | None] = mapped_column(JSONColumn, default=list)
    desired_industries: Mapped[list | None] = mapped_column(JSONColumn, default=list)
    desired_employment_types: Mapped[list | None] = mapped_column(JSONColumn, default=list)
    desired_locations: Mapped[list | None] = mapped_column(JSONColumn, default=list)
    remote_preference: Mapped[str | None] = mapped_column(String(20))
    salary_min: Mapped[int | None] = mapped_column(Integer)
    salary_max: Mapped[int | None] = mapped_column(Integer)
    salary_currency: Mapped[str] = mapped_column(String(3), default="USD", nullable=False)
    open_to_relocation: Mapped[bool | None] = mapped_column(Boolean)

    # -- work authorization -------------------------------------------------
    # Legally significant. Supplied explicitly by the user; never inferred from a
    # resume, and never generated by a model.
    authorization_country: Mapped[str | None] = mapped_column(String(120))
    authorization_type: Mapped[str | None] = mapped_column(String(40))
    authorization_expires_on: Mapped[date | None] = mapped_column(Date)
    requires_sponsorship_now: Mapped[bool | None] = mapped_column(Boolean)
    requires_sponsorship_future: Mapped[bool | None] = mapped_column(Boolean)
    work_authorization_confirmed_at: Mapped[date | None] = mapped_column(Date)

    user: Mapped[User] = relationship(back_populates="profile")  # noqa: F821

    @property
    def full_name(self) -> str:
        return " ".join(part for part in (self.first_name, self.last_name) if part).strip()

    @property
    def work_authorization_declared(self) -> bool:
        """True only when the user has explicitly answered every authorization field."""
        return (
            self.authorization_country is not None
            and self.authorization_type is not None
            and self.requires_sponsorship_now is not None
            and self.requires_sponsorship_future is not None
        )


class Education(Base, UUIDPrimaryKeyMixin, TimestampMixin, SoftDeleteMixin):
    __tablename__ = "education"
    __table_args__ = (Index("ix_education_user_sort", "user_id", "sort_order"),)

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUIDColumn, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    institution: Mapped[str] = mapped_column(String(255), nullable=False)
    degree: Mapped[str | None] = mapped_column(String(180))
    field_of_study: Mapped[str | None] = mapped_column(String(180))
    location: Mapped[str | None] = mapped_column(String(180))
    start_date: Mapped[date | None] = mapped_column(Date)
    end_date: Mapped[date | None] = mapped_column(Date)
    is_current: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    gpa: Mapped[float | None] = mapped_column(Numeric(3, 2))
    relevant_coursework: Mapped[list | None] = mapped_column(JSONColumn, default=list)
    sort_order: Mapped[int] = mapped_column(Integer, default=0, nullable=False)


class Experience(Base, UUIDPrimaryKeyMixin, TimestampMixin, SoftDeleteMixin):
    __tablename__ = "experience"
    __table_args__ = (Index("ix_experience_user_sort", "user_id", "sort_order"),)

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUIDColumn, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    company: Mapped[str] = mapped_column(String(255), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    location: Mapped[str | None] = mapped_column(String(180))
    employment_type: Mapped[str | None] = mapped_column(String(30))
    start_date: Mapped[date | None] = mapped_column(Date)
    end_date: Mapped[date | None] = mapped_column(Date)
    is_current: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    #: User-authored or user-approved bullets. Tailoring may reorder and rephrase these
    #: but may not introduce a claim that is not grounded here.
    accomplishments: Mapped[list | None] = mapped_column(JSONColumn, default=list)
    technologies: Mapped[list | None] = mapped_column(JSONColumn, default=list)
    skills: Mapped[list | None] = mapped_column(JSONColumn, default=list)
    sort_order: Mapped[int] = mapped_column(Integer, default=0, nullable=False)


class Skill(Base, UUIDPrimaryKeyMixin, TimestampMixin, SoftDeleteMixin):
    __tablename__ = "skills"
    __table_args__ = (
        UniqueConstraint("user_id", "normalized_name", name="uq_skills_user_name"),
        Index("ix_skills_user_category", "user_id", "category"),
    )

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUIDColumn, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    normalized_name: Mapped[str] = mapped_column(String(120), nullable=False)
    category: Mapped[str] = mapped_column(String(30), default="other", nullable=False)
    years_experience: Mapped[float | None] = mapped_column(Numeric(4, 1))
    proficiency: Mapped[str | None] = mapped_column(String(20))
    #: True once the user has explicitly confirmed the skill (as opposed to it having
    #: been suggested by the resume parser).
    is_verified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    last_used_year: Mapped[int | None] = mapped_column(Integer)


class Certification(Base, UUIDPrimaryKeyMixin, TimestampMixin, SoftDeleteMixin):
    __tablename__ = "certifications"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUIDColumn, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    issuer: Mapped[str | None] = mapped_column(String(255))
    issued_on: Mapped[date | None] = mapped_column(Date)
    expires_on: Mapped[date | None] = mapped_column(Date)
    credential_id: Mapped[str | None] = mapped_column(String(180))
    credential_url: Mapped[str | None] = mapped_column(String(500))
    is_verified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)


class Project(Base, UUIDPrimaryKeyMixin, TimestampMixin, SoftDeleteMixin):
    __tablename__ = "projects"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUIDColumn, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    role: Mapped[str | None] = mapped_column(String(180))
    url: Mapped[str | None] = mapped_column(String(500))
    description: Mapped[str | None] = mapped_column(Text)
    highlights: Mapped[list | None] = mapped_column(JSONColumn, default=list)
    technologies: Mapped[list | None] = mapped_column(JSONColumn, default=list)
    start_date: Mapped[date | None] = mapped_column(Date)
    end_date: Mapped[date | None] = mapped_column(Date)
    sort_order: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
